- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    home: /app
    system: true
    comment: "roboshop system user" 
    shell: /sbin/nologin

- name: remove app directory ## Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
  ansible.builtin.file:
    path: /app
    state: absent
    
- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Delete {{ component }} code
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Download the {{ component }} code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: extract the {{ component }} code
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes
  